### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/management-api#14]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by jim-krueger** [comment]
Need to change dependency information for ejb-api when available.  Cannot close until then.

**Comment by m0mus** [comment]
EJB 3.2.3 has been released to staging. You can proceed.
https://oss.sonatype.org/content/groups/staging/jakarta/ejb/jakarta.ejb-api/

**Comment by jim-krueger** [comment]
Dependencies updated

**Comment by MarkWareham** [comment]
This is reported as in staging, but doesn't appear to be?  https://oss.sonatype.org/content/groups/staging/jakarta/

**Comment by smillidge** [comment]
I'll reopen this for now

**Comment by jim-krueger** [comment]
Completed:   https://oss.sonatype.org/content/groups/staging/jakarta/management/j2ee/jakarta.management.j2ee-api/
